package com.example.pokequiz

object QuizList {
    val quizList: List<String> = listOf(
        "{ \"question\": \"What type is Pikachu?\", \"options\": [\"Electric\", \"Fire\", \"Water\", \"Grass\"], \"answer\": \"Electric\" }",
        "{ \"question\": \"Which Pokémon is known as the Flame Pokémon?\", \"options\": [\"Charmander\", \"Squirtle\", \"Bulbasaur\", \"Pidgey\"], \"answer\": \"Charmander\" }",
        "{ \"question\": \"What is the final evolution of Bulbasaur?\", \"options\": [\"Ivysaur\", \"Venusaur\", \"Meganium\", \"Tangrowth\"], \"answer\": \"Venusaur\" }",
        "{ \"question\": \"Which Pokémon evolves into Raichu?\", \"options\": [\"Pichu\", \"Pikachu\", \"Magnemite\", \"Electabuzz\"], \"answer\": \"Pikachu\" }",
        "{ \"question\": \"What type is Squirtle?\", \"options\": [\"Water\", \"Ice\", \"Electric\", \"Rock\"], \"answer\": \"Water\" }",
        "{ \"question\": \"Which Pokémon is number 1 in the Pokédex?\", \"options\": [\"Bulbasaur\", \"Charmander\", \"Pikachu\", \"Mew\"], \"answer\": \"Bulbasaur\" }",
        "{ \"question\": \"Which Pokémon can evolve into multiple different forms?\", \"options\": [\"Eevee\", \"Ditto\", \"Meowth\", \"Snorlax\"], \"answer\": \"Eevee\" }",
        "{ \"question\": \"What type is Charizard?\", \"options\": [\"Fire/Flying\", \"Fire/Dragon\", \"Flying/Dragon\", \"Fire\"], \"answer\": \"Fire/Flying\" }",
        "{ \"question\": \"Which Pokémon is known for sleeping most of the time?\", \"options\": [\"Snorlax\", \"Slaking\", \"Komala\", \"Slowpoke\"], \"answer\": \"Snorlax\" }",
        "{ \"question\": \"Which Pokémon is famous for copying opponents?\", \"options\": [\"Ditto\", \"Mew\", \"Zoroark\", \"Smeargle\"], \"answer\": \"Ditto\" }",
        "{ \"question\": \"What type is Gengar?\", \"options\": [\"Ghost/Poison\", \"Dark/Ghost\", \"Poison\", \"Ghost\"], \"answer\": \"Ghost/Poison\" }",
        "{ \"question\": \"Which Pokémon evolves from Magikarp?\", \"options\": [\"Gyarados\", \"Milotic\", \"Sharpedo\", \"Seaking\"], \"answer\": \"Gyarados\" }",
        "{ \"question\": \"Which Pokémon is known as the Mouse Pokémon?\", \"options\": [\"Pikachu\", \"Rattata\", \"Sandshrew\", \"Dedenne\"], \"answer\": \"Pikachu\" }",
        "{ \"question\": \"What type is Onix?\", \"options\": [\"Rock/Ground\", \"Rock\", \"Ground\", \"Steel\"], \"answer\": \"Rock/Ground\" }",
        "{ \"question\": \"Which Pokémon is a legendary bird?\", \"options\": [\"Articuno\", \"Lugia\", \"Ho-Oh\", \"Zapdos\"], \"answer\": \"Articuno\" }",
        "{ \"question\": \"What type is Jigglypuff?\", \"options\": [\"Normal/Fairy\", \"Fairy\", \"Normal\", \"Psychic\"], \"answer\": \"Normal/Fairy\" }",
        "{ \"question\": \"Which Pokémon uses a leek as a weapon?\", \"options\": [\"Farfetch'd\", \"Doduo\", \"Scyther\", \"Cubone\"], \"answer\": \"Farfetch'd\" }",
        "{ \"question\": \"Which Pokémon evolves using a Thunder Stone?\", \"options\": [\"Pikachu\", \"Clefairy\", \"Jigglypuff\", \"Eevee\"], \"answer\": \"Pikachu\" }",
        "{ \"question\": \"What type is Mewtwo?\", \"options\": [\"Psychic\", \"Fairy\", \"Ghost\", \"Dark\"], \"answer\": \"Psychic\" }",
        "{ \"question\": \"Which Pokémon is known as the Seed Pokémon?\", \"options\": [\"Bulbasaur\", \"Oddish\", \"Chikorita\", \"Bellsprout\"], \"answer\": \"Bulbasaur\" }",
        "{ \"question\": \"What is the evolution of Ivysaur?\", \"options\": [\"Venusaur\", \"Meganium\", \"Tangela\", \"Vileplume\"], \"answer\": \"Venusaur\" }",
        "{ \"question\": \"Which Pokémon is a Water/Flying type?\", \"options\": [\"Gyarados\", \"Pelipper\", \"Mantine\", \"Wingull\"], \"answer\": \"Gyarados\" }",
        "{ \"question\": \"Which Pokémon is known for saying its own name?\", \"options\": [\"Pikachu\", \"Meowth\", \"Eevee\", \"Psyduck\"], \"answer\": \"Pikachu\" }",
        "{ \"question\": \"What type is Alakazam?\", \"options\": [\"Psychic\", \"Fairy\", \"Ghost\", \"Normal\"], \"answer\": \"Psychic\" }",
        "{ \"question\": \"Which Pokémon is a fossil Pokémon?\", \"options\": [\"Omanyte\", \"Lapras\", \"Relicanth\", \"Kabuto\"], \"answer\": \"Omanyte\" }",
        "{ \"question\": \"Which Pokémon evolves from Abra?\", \"options\": [\"Kadabra\", \"Alakazam\", \"Hypno\", \"Espeon\"], \"answer\": \"Kadabra\" }",
        "{ \"question\": \"What type is Machamp?\", \"options\": [\"Fighting\", \"Rock\", \"Ground\", \"Normal\"], \"answer\": \"Fighting\" }",
        "{ \"question\": \"Which Pokémon carries a bone?\", \"options\": [\"Cubone\", \"Marowak\", \"Kangaskhan\", \"Sandslash\"], \"answer\": \"Cubone\" }",
        "{ \"question\": \"Which Pokémon is known as the Electric Mouse Pokémon?\", \"options\": [\"Pikachu\", \"Plusle\", \"Minun\", \"Dedenne\"], \"answer\": \"Pikachu\" }",
        "{ \"question\": \"What type is Dragonite?\", \"options\": [\"Dragon/Flying\", \"Dragon\", \"Flying\", \"Water/Dragon\"], \"answer\": \"Dragon/Flying\" }",
        "{ \"question\": \"Which Pokémon evolves into Butterfree?\", \"options\": [\"Metapod\", \"Weedle\", \"Caterpie\", \"Venonat\"], \"answer\": \"Metapod\" }",
        "{ \"question\": \"What type is Lapras?\", \"options\": [\"Water/Ice\", \"Ice\", \"Water\", \"Ice/Fairy\"], \"answer\": \"Water/Ice\" }",
        "{ \"question\": \"Which Pokémon is known as the Balloon Pokémon?\", \"options\": [\"Jigglypuff\", \"Drifloon\", \"Wigglytuff\", \"Clefairy\"], \"answer\": \"Jigglypuff\" }",
        "{ \"question\": \"Which Pokémon evolves using a Fire Stone?\", \"options\": [\"Vulpix\", \"Growlithe\", \"Eevee\", \"Ponyta\"], \"answer\": \"Vulpix\" }",
        "{ \"question\": \"What type is Scyther?\", \"options\": [\"Bug/Flying\", \"Bug\", \"Flying\", \"Bug/Steel\"], \"answer\": \"Bug/Flying\" }",
        "{ \"question\": \"Which Pokémon is a Psychic/Fairy type?\", \"options\": [\"Mr. Mime\", \"Clefable\", \"Gardevoir\", \"Alakazam\"], \"answer\": \"Mr. Mime\" }",
        "{ \"question\": \"Which Pokémon is known as the Poison Pin Pokémon?\", \"options\": [\"Nidoran♀\", \"Nidoran♂\", \"Ekans\", \"Zubat\"], \"answer\": \"Nidoran♀\" }",
        "{ \"question\": \"What type is Vaporeon?\", \"options\": [\"Water\", \"Ice\", \"Fairy\", \"Normal\"], \"answer\": \"Water\" }",
        "{ \"question\": \"Which Pokémon evolves into Nidoking?\", \"options\": [\"Nidorino\", \"Nidoran♂\", \"Nidoqueen\", \"Rhydon\"], \"answer\": \"Nidorino\" }",
        "{ \"question\": \"Which Pokémon is known as the Fox Pokémon?\", \"options\": [\"Vulpix\", \"Zorua\", \"Eevee\", \"Fennekin\"], \"answer\": \"Vulpix\" }",
        "{ \"question\": \"What type is Poliwrath?\", \"options\": [\"Water/Fighting\", \"Water\", \"Fighting\", \"Ice/Fighting\"], \"answer\": \"Water/Fighting\" }",
        "{ \"question\": \"Which Pokémon is famous for explosions?\", \"options\": [\"Voltorb\", \"Electrode\", \"Koffing\", \"Geodude\"], \"answer\": \"Voltorb\" }",
        "{ \"question\": \"What type is Sandshrew?\", \"options\": [\"Ground\", \"Rock\", \"Normal\", \"Steel\"], \"answer\": \"Ground\" }",
        "{ \"question\": \"Which Pokémon is known as the Virtual Pokémon?\", \"options\": [\"Porygon\", \"Magnemite\", \"Ditto\", \"Rotom\"], \"answer\": \"Porygon\" }",
        "{ \"question\": \"Which Pokémon evolves into Crobat?\", \"options\": [\"Golbat\", \"Zubat\", \"Noivern\", \"Swoobat\"], \"answer\": \"Golbat\" }",
        "{ \"question\": \"What type is Clefairy?\", \"options\": [\"Fairy\", \"Normal\", \"Psychic\", \"Normal/Fairy\"], \"answer\": \"Fairy\" }",
        "{ \"question\": \"Which Pokémon is known as the Sleeping Pokémon?\", \"options\": [\"Snorlax\", \"Komala\", \"Slowpoke\", \"Hypno\"], \"answer\": \"Snorlax\" }",
        "{ \"question\": \"What type is Aerodactyl?\", \"options\": [\"Rock/Flying\", \"Dragon/Flying\", \"Rock\", \"Flying\"], \"answer\": \"Rock/Flying\" }",
        "{ \"question\": \"Which Pokémon evolves into Arcanine?\", \"options\": [\"Growlithe\", \"Vulpix\", \"Houndour\", \"Eevee\"], \"answer\": \"Growlithe\" }",
        "{ \"question\": \"Which Pokémon is the first in the Johto Pokédex?\", \"options\": [\"Chikorita\", \"Cyndaquil\", \"Totodile\", \"Sentret\"], \"answer\": \"Chikorita\" }",
        "{ \"question\": \"What type is Chikorita?\", \"options\": [\"Grass\", \"Grass/Fairy\", \"Normal\", \"Bug\"], \"answer\": \"Grass\" }",
        "{ \"question\": \"Which Johto starter is a Fire type?\", \"options\": [\"Cyndaquil\", \"Chikorita\", \"Totodile\", \"Houndour\"], \"answer\": \"Cyndaquil\" }",
        "{ \"question\": \"What type is Totodile?\", \"options\": [\"Water\", \"Ice\", \"Ground\", \"Dragon\"], \"answer\": \"Water\" }",
        "{ \"question\": \"Which Pokémon evolves into Meganium?\", \"options\": [\"Bayleef\", \"Chikorita\", \"Gloom\", \"Bellossom\"], \"answer\": \"Bayleef\" }",
        "{ \"question\": \"Which Pokémon evolves into Typhlosion?\", \"options\": [\"Quilava\", \"Cyndaquil\", \"Magmar\", \"Slugma\"], \"answer\": \"Quilava\" }",
        "{ \"question\": \"Which Pokémon evolves into Feraligatr?\", \"options\": [\"Croconaw\", \"Totodile\", \"Gyarados\", \"Seadra\"], \"answer\": \"Croconaw\" }",
        "{ \"question\": \"Which Johto Pokémon is known as the Spike Ball Pokémon?\", \"options\": [\"Qwilfish\", \"Corsola\", \"Remoraid\", \"Mantine\"], \"answer\": \"Qwilfish\" }",
        "{ \"question\": \"What type is Ampharos?\", \"options\": [\"Electric\", \"Electric/Dragon\", \"Electric/Fairy\", \"Normal\"], \"answer\": \"Electric\" }",
        "{ \"question\": \"Which Pokémon evolves from Mareep?\", \"options\": [\"Flaaffy\", \"Ampharos\", \"Wooloo\", \"Electabuzz\"], \"answer\": \"Flaaffy\" }",
        "{ \"question\": \"Which Pokémon is known as the Big Jaw Pokémon?\", \"options\": [\"Feraligatr\", \"Totodile\", \"Sharpedo\", \"Krookodile\"], \"answer\": \"Feraligatr\" }",
        "{ \"question\": \"What type is Houndoom?\", \"options\": [\"Dark/Fire\", \"Fire\", \"Dark\", \"Fire/Ghost\"], \"answer\": \"Dark/Fire\" }",
        "{ \"question\": \"Which Pokémon introduced the Dark type in Johto?\", \"options\": [\"Umbreon\", \"Houndour\", \"Sneasel\", \"Murkrow\"], \"answer\": \"Umbreon\" }",
        "{ \"question\": \"Which Pokémon evolves into Umbreon?\", \"options\": [\"Eevee\", \"Espeon\", \"Sneasel\", \"Murkrow\"], \"answer\": \"Eevee\" }",
        "{ \"question\": \"What type is Espeon?\", \"options\": [\"Psychic\", \"Fairy\", \"Ghost\", \"Normal\"], \"answer\": \"Psychic\" }",
        "{ \"question\": \"Which Johto Pokémon is known as the Aurora Pokémon?\", \"options\": [\"Suicune\", \"Raikou\", \"Entei\", \"Lugia\"], \"answer\": \"Suicune\" }",
        "{ \"question\": \"Which Legendary Pokémon represents thunder in Johto?\", \"options\": [\"Raikou\", \"Entei\", \"Suicune\", \"Zapdos\"], \"answer\": \"Raikou\" }",
        "{ \"question\": \"Which Legendary Pokémon represents fire in Johto?\", \"options\": [\"Entei\", \"Raikou\", \"Suicune\", \"Moltres\"], \"answer\": \"Entei\" }",
        "{ \"question\": \"Which Pokémon is the guardian of the seas in Johto?\", \"options\": [\"Lugia\", \"Ho-Oh\", \"Suicune\", \"Kyogre\"], \"answer\": \"Lugia\" }",
        "{ \"question\": \"Which Pokémon is said to resurrect Pokémon in Johto lore?\", \"options\": [\"Ho-Oh\", \"Lugia\", \"Celebi\", \"Entei\"], \"answer\": \"Ho-Oh\" }",
        "{ \"question\": \"What type is Skarmory?\", \"options\": [\"Steel/Flying\", \"Flying\", \"Steel\", \"Rock/Flying\"], \"answer\": \"Steel/Flying\" }",
        "{ \"question\": \"Which Pokémon travels through time in Johto?\", \"options\": [\"Celebi\", \"Dialga\", \"Mew\", \"Jirachi\"], \"answer\": \"Celebi\" }",
        "{ \"question\": \"Which Johto Pokémon is known for carrying logs?\", \"options\": [\"Sudowoodo\", \"Heracross\", \"Donphan\", \"Ursaring\"], \"answer\": \"Sudowoodo\" }",
        "{ \"question\": \"What type is Heracross?\", \"options\": [\"Bug/Fighting\", \"Bug\", \"Fighting\", \"Bug/Dark\"], \"answer\": \"Bug/Fighting\" }",
        "{ \"question\": \"Which Pokémon is the first in the Hoenn Pokédex?\", \"options\": [\"Treecko\", \"Torchic\", \"Mudkip\", \"Ralts\"], \"answer\": \"Treecko\" }",
        "{ \"question\": \"What type is Treecko?\", \"options\": [\"Grass\", \"Grass/Ground\", \"Bug\", \"Grass/Dragon\"], \"answer\": \"Grass\" }",
        "{ \"question\": \"Which Hoenn starter is a Fire type?\", \"options\": [\"Torchic\", \"Treecko\", \"Mudkip\", \"Combusken\"], \"answer\": \"Torchic\" }",
        "{ \"question\": \"Which Hoenn starter is a Water type?\", \"options\": [\"Mudkip\", \"Torchic\", \"Treecko\", \"Lotad\"], \"answer\": \"Mudkip\" }",
        "{ \"question\": \"Which Pokémon evolves into Sceptile?\", \"options\": [\"Grovyle\", \"Treecko\", \"Ralts\", \"Lotad\"], \"answer\": \"Grovyle\" }",
        "{ \"question\": \"Which Pokémon evolves into Blaziken?\", \"options\": [\"Combusken\", \"Torchic\", \"Monferno\", \"Chimchar\"], \"answer\": \"Combusken\" }",
        "{ \"question\": \"Which Pokémon evolves into Swampert?\", \"options\": [\"Marshtomp\", \"Mudkip\", \"Lotad\", \"Lombre\"], \"answer\": \"Marshtomp\" }",
        "{ \"question\": \"Which Hoenn Pokémon is known as the Shellfish Pokémon?\", \"options\": [\"Clamperl\", \"Corphish\", \"Shelgon\", \"Crawdaunt\"], \"answer\": \"Clamperl\" }",
        "{ \"question\": \"What type is Gardevoir in Hoenn?\", \"options\": [\"Psychic/Fairy\", \"Psychic\", \"Fairy\", \"Psychic/Grass\"], \"answer\": \"Psychic\" }",
        "{ \"question\": \"Which Pokémon evolves from Ralts?\", \"options\": [\"Kirlia\", \"Gardevoir\", \"Gallade\", \"Medicham\"], \"answer\": \"Kirlia\" }",
        "{ \"question\": \"Which Pokémon evolves from Kirlia into Hoenn's Psychic type?\", \"options\": [\"Gardevoir\", \"Gallade\", \"Metagross\", \"Ludicolo\"], \"answer\": \"Gardevoir\" }",
        "{ \"question\": \"Which Legendary Pokémon represents the sea in Hoenn?\", \"options\": [\"Kyogre\", \"Groudon\", \"Rayquaza\", \"Regice\"], \"answer\": \"Kyogre\" }",
        "{ \"question\": \"Which Legendary Pokémon represents the land in Hoenn?\", \"options\": [\"Groudon\", \"Kyogre\", \"Rayquaza\", \"Regirock\"], \"answer\": \"Groudon\" }",
        "{ \"question\": \"Which Legendary Pokémon controls the sky in Hoenn?\", \"options\": [\"Rayquaza\", \"Latios\", \"Latias\", \"Registeel\"], \"answer\": \"Rayquaza\" }",
        "{ \"question\": \"What type is Aggron?\", \"options\": [\"Steel/Rock\", \"Steel\", \"Rock\", \"Steel/Ground\"], \"answer\": \"Steel/Rock\" }",
        "{ \"question\": \"Which Pokémon evolves from Aron?\", \"options\": [\"Lairon\", \"Aggron\", \"Nosepass\", \"Meditite\"], \"answer\": \"Lairon\" }",
        "{ \"question\": \"Which Pokémon is known as the Twin Pokémon in Hoenn?\", \"options\": [\"Latios\", \"Latias\", \"Registeel\", \"Metagross\"], \"answer\": \"Latios\" }",
        "{ \"question\": \"Which Pokémon is known as the Eon Pokémon in Hoenn?\", \"options\": [\"Latias\", \"Latios\", \"Rayquaza\", \"Jirachi\"], \"answer\": \"Latias\" }",
        "{ \"question\": \"Which Pokémon is a Water/Grass type in Hoenn?\", \"options\": [\"Ludicolo\", \"Lotad\", \"Lombre\", \"Surskit\"], \"answer\": \"Ludicolo\" }",
        "{ \"question\": \"Which Pokémon evolves into Ludicolo?\", \"options\": [\"Lombre\", \"Lotad\", \"Seedot\", \"Nuzleaf\"], \"answer\": \"Lombre\" }",
        "{ \"question\": \"Which Hoenn Pokémon is known as the Clay Doll Pokémon?\", \"options\": [\"Golett\", \"Baltoy\", \"Grovyle\", \"Solrock\"], \"answer\": \"Baltoy\" }",
        "{ \"question\": \"What type is Shiftry?\", \"options\": [\"Grass/Dark\", \"Grass\", \"Dark\", \"Grass/Ghost\"], \"answer\": \"Grass/Dark\" }",
        "{ \"question\": \"Which Pokémon evolves from Nuzleaf?\", \"options\": [\"Shiftry\", \"Tropius\", \"Sceptile\", \"Lombre\"], \"answer\": \"Shiftry\" }",
        "{ \"question\": \"Which Pokémon is known as the Meteor Pokémon in Hoenn?\", \"options\": [\"Registeel\", \"Solrock\", \"Lunatone\", \"Metagross\"], \"answer\": \"Registeel\" }",
        "{ \"question\": \"Which Pokémon is the first in the Sinnoh Pokédex?\", \"options\": [\"Turtwig\", \"Chimchar\", \"Piplup\", \"Starly\"], \"answer\": \"Turtwig\" }",
        "{ \"question\": \"What type is Turtwig?\", \"options\": [\"Grass\", \"Grass/Ground\", \"Grass/Steel\", \"Grass/Water\"], \"answer\": \"Grass\" }",
        "{ \"question\": \"Which Sinnoh starter is a Fire type?\", \"options\": [\"Chimchar\", \"Turtwig\", \"Piplup\", \"Monferno\"], \"answer\": \"Chimchar\" }",
        "{ \"question\": \"Which Sinnoh starter is a Water type?\", \"options\": [\"Piplup\", \"Turtwig\", \"Chimchar\", \"Buizel\"], \"answer\": \"Piplup\" }",
        "{ \"question\": \"Which Pokémon evolves into Torterra?\", \"options\": [\"Grotle\", \"Turtwig\", \"Leafeon\", \"Grovyle\"], \"answer\": \"Grotle\" }",
        "{ \"question\": \"Which Pokémon evolves into Infernape?\", \"options\": [\"Monferno\", \"Chimchar\", \"Blaziken\", \"Combusken\"], \"answer\": \"Monferno\" }",
        "{ \"question\": \"Which Pokémon evolves into Empoleon?\", \"options\": [\"Prinplup\", \"Piplup\", \"Kingler\", \"Sealeo\"], \"answer\": \"Prinplup\" }",
        "{ \"question\": \"Which Sinnoh Pokémon is known as the Seed Pokémon?\", \"options\": [\"Turtwig\", \"Chikorita\", \"Bulbasaur\", \"Shaymin\"], \"answer\": \"Turtwig\" }",
        "{ \"question\": \"What type is Luxray?\", \"options\": [\"Electric\", \"Electric/Dark\", \"Dark\", \"Electric/Steel\"], \"answer\": \"Electric\" }",
        "{ \"question\": \"Which Pokémon evolves from Shinx?\", \"options\": [\"Luxio\", \"Luxray\", \"Electivire\", \"Jolteon\"], \"answer\": \"Luxio\" }",
        "{ \"question\": \"Which Sinnoh Legendary is known as the Lake Guardian?\", \"options\": [\"Uxie\", \"Mesprit\", \"Azelf\", \"Cresselia\"], \"answer\": \"Uxie\" }",
        "{ \"question\": \"Which Sinnoh Legendary represents emotion?\", \"options\": [\"Mesprit\", \"Azelf\", \"Uxie\", \"Dialga\"], \"answer\": \"Mesprit\" }",
        "{ \"question\": \"Which Sinnoh Legendary represents willpower?\", \"options\": [\"Azelf\", \"Mesprit\", \"Uxie\", \"Palkia\"], \"answer\": \"Azelf\" }",
        "{ \"question\": \"Which Sinnoh Pokémon controls time?\", \"options\": [\"Dialga\", \"Palkia\", \"Giratina\", \"Regigigas\"], \"answer\": \"Dialga\" }",
        "{ \"question\": \"Which Sinnoh Pokémon controls space?\", \"options\": [\"Palkia\", \"Dialga\", \"Giratina\", \"Cresselia\"], \"answer\": \"Palkia\" }",
        "{ \"question\": \"Which Sinnoh Pokémon dwells in the Distortion World?\", \"options\": [\"Giratina\", \"Dialga\", \"Palkia\", \"Registeel\"], \"answer\": \"Giratina\" }",
        "{ \"question\": \"What type is Roserade?\", \"options\": [\"Grass/Poison\", \"Grass\", \"Poison\", \"Grass/Fairy\"], \"answer\": \"Grass/Poison\" }",
        "{ \"question\": \"Which Pokémon evolves from Roselia in Sinnoh?\", \"options\": [\"Roserade\", \"Roselia\", \"Budew\", \"Bellossom\"], \"answer\": \"Roserade\" }",
        "{ \"question\": \"Which Sinnoh Pokémon is known as the Fang Pokémon?\", \"options\": [\"Lucario\", \"Gible\", \"Gabite\", \"Garchomp\"], \"answer\": \"Lucario\" }",
        "{ \"question\": \"Which Pokémon evolves from Riolu?\", \"options\": [\"Lucario\", \"Garchomp\", \"Blaziken\", \"Infernape\"], \"answer\": \"Lucario\" }",
        "{ \"question\": \"What type is Garchomp?\", \"options\": [\"Dragon/Ground\", \"Dragon\", \"Ground/Dragon\", \"Dragon/Steel\"], \"answer\": \"Dragon/Ground\" }",
        "{ \"question\": \"Which Pokémon evolves from Gabite?\", \"options\": [\"Garchomp\", \"Gible\", \"Gyarados\", \"Dragonite\"], \"answer\": \"Garchomp\" }",
        "{ \"question\": \"Which Sinnoh Pokémon is known as the Moonlight Pokémon?\", \"options\": [\"Cresselia\", \"Lunatone\", \"Solrock\", \"Chimecho\"], \"answer\": \"Cresselia\" }",
        "{ \"question\": \"Which Sinnoh Pokémon is known as the Lunar Pokémon?\", \"options\": [\"Lunatone\", \"Solrock\", \"Cresselia\", \"Bruxish\"], \"answer\": \"Lunatone\" }",
        "{ \"question\": \"Which Sinnoh Pokémon is known as the Sun Pokémon?\", \"options\": [\"Solrock\", \"Lunatone\", \"Cresselia\", \"Heliolisk\"], \"answer\": \"Solrock\" }",
        "{ \"question\": \"Which Sinnoh Pokémon is the Legendary Regi of Sinnoh?\", \"options\": [\"Regigigas\", \"Registeel\", \"Regice\", \"Regirock\"], \"answer\": \"Regigigas\" }",
        "{ \"question\": \"Which Sinnoh Pokémon is part Steel type Legendary trio?\", \"options\": [\"Registeel\", \"Regice\", \"Regirock\", \"Regigigas\"], \"answer\": \"Registeel\" }",
        "{ \"question\": \"Which Pokémon is the first in the Unova Pokédex?\", \"options\": [\"Victini\", \"Snivy\", \"Tepig\", \"Oshawott\"], \"answer\": \"Victini\" }",
        "{ \"question\": \"What type is Snivy?\", \"options\": [\"Grass\", \"Grass/Poison\", \"Grass/Dragon\", \"Normal\"], \"answer\": \"Grass\" }",
        "{ \"question\": \"Which Unova starter is a Fire type?\", \"options\": [\"Tepig\", \"Snivy\", \"Oshawott\", \"Pignite\"], \"answer\": \"Tepig\" }",
        "{ \"question\": \"Which Unova starter is a Water type?\", \"options\": [\"Oshawott\", \"Snivy\", \"Tepig\", \"Dewott\"], \"answer\": \"Oshawott\" }",
        "{ \"question\": \"Which Pokémon evolves into Serperior?\", \"options\": [\"Servine\", \"Snivy\", \"Leavanny\", \"Petilil\"], \"answer\": \"Servine\" }",
        "{ \"question\": \"Which Pokémon evolves into Emboar?\", \"options\": [\"Pignite\", \"Tepig\", \"Simisear\", \"Pansear\"], \"answer\": \"Pignite\" }",
        "{ \"question\": \"Which Pokémon evolves into Samurott?\", \"options\": [\"Dewott\", \"Oshawott\", \"Dartrix\", \"Fomantis\"], \"answer\": \"Dewott\" }",
        "{ \"question\": \"Which Unova Pokémon is known as the Victory Pokémon?\", \"options\": [\"Victini\", \"Zekrom\", \"Reshiram\", \"Keldeo\"], \"answer\": \"Victini\" }",
        "{ \"question\": \"Which Legendary Pokémon represents fire in Unova?\", \"options\": [\"Reshiram\", \"Zekrom\", \"Victini\", \"Heatmor\"], \"answer\": \"Reshiram\" }",
        "{ \"question\": \"Which Legendary Pokémon represents electricity in Unova?\", \"options\": [\"Zekrom\", \"Reshiram\", \"Thundurus\", \"Rotom\"], \"answer\": \"Zekrom\" }",
        "{ \"question\": \"Which Pokémon is part of the Tao trio in Unova?\", \"options\": [\"Reshiram\", \"Zekrom\", \"Kyurem\", \"All of the above\"], \"answer\": \"All of the above\" }",
        "{ \"question\": \"What type is Excadrill?\", \"options\": [\"Ground/Steel\", \"Ground\", \"Steel\", \"Rock/Ground\"], \"answer\": \"Ground/Steel\" }",
        "{ \"question\": \"Which Pokémon evolves from Drilbur?\", \"options\": [\"Excadrill\", \"Drilbur\", \"Sandile\", \"Trapinch\"], \"answer\": \"Excadrill\" }",
        "{ \"question\": \"Which Unova Pokémon is known as the Fox Pokémon?\", \"options\": [\"Zorua\", \"Zoroark\", \"Fennekin\", \"Vulpix\"], \"answer\": \"Zorua\" }",
        "{ \"question\": \"Which Pokémon evolves into Zoroark?\", \"options\": [\"Zorua\", \"Zorak\", \"Zubat\", \"Zangoose\"], \"answer\": \"Zorua\" }",
        "{ \"question\": \"Which Unova Pokémon is known as the Thunderbolt Pokémon?\", \"options\": [\"Jolteon\", \"Emolga\", \"Zebstrika\", \"Blitzle\"], \"answer\": \"Blitzle\" }",
        "{ \"question\": \"Which Pokémon evolves into Zebstrika?\", \"options\": [\"Blitzle\", \"Emolga\", \"Joltik\", \"Tynamo\"], \"answer\": \"Blitzle\" }",
        "{ \"question\": \"What type is Hydreigon?\", \"options\": [\"Dark/Dragon\", \"Dragon\", \"Dark\", \"Dragon/Flying\"], \"answer\": \"Dark/Dragon\" }",
        "{ \"question\": \"Which Pokémon evolves from Zweilous?\", \"options\": [\"Hydreigon\", \"Deino\", \"Zweilous\", \"Haxorus\"], \"answer\": \"Hydreigon\" }",
        "{ \"question\": \"Which Pokémon is known as the Jet Pokémon?\", \"options\": [\"Tornadus\", \"Thundurus\", \"Landorus\", \"Virizion\"], \"answer\": \"Tornadus\" }",
        "{ \"question\": \"Which Pokémon is the Legendary Musketeer trio in Unova?\", \"options\": [\"Tornadus, Thundurus, Landorus\", \"Reshiram, Zekrom, Kyurem\", \"Cobalion, Terrakion, Virizion\", \"Victini, Keldeo, Meloetta\"], \"answer\": \"Tornadus, Thundurus, Landorus\" }",
        "{ \"question\": \"Which Pokémon evolves into Reuniclus?\", \"options\": [\"Duosion\", \"Solosis\", \"Gothita\", \"Elgyem\"], \"answer\": \"Duosion\" }",
        "{ \"question\": \"Which Pokémon evolves from Solosis?\", \"options\": [\"Duosion\", \"Reuniclus\", \"Gothorita\", \"Gothitelle\"], \"answer\": \"Duosion\" }",
        "{ \"question\": \"Which Unova Pokémon is known as the Iron Treads Pokémon?\", \"options\": [\"Ferrothorn\", \"Stunfisk\", \"Klinklang\", \"Excadrill\"], \"answer\": \"Excadrill\" }",
        "{ \"question\": \"Which Pokémon is the first in the Kalos Pokédex?\", \"options\": [\"Chespin\", \"Fennekin\", \"Froakie\", \"Bunnelby\"], \"answer\": \"Chespin\" }",
        "{ \"question\": \"What type is Chespin?\", \"options\": [\"Grass\", \"Grass/Ground\", \"Grass/Fighting\", \"Grass/Bug\"], \"answer\": \"Grass\" }",
        "{ \"question\": \"Which Kalos starter is a Fire type?\", \"options\": [\"Fennekin\", \"Chespin\", \"Froakie\", \"Braixen\"], \"answer\": \"Fennekin\" }",
        "{ \"question\": \"Which Kalos starter is a Water type?\", \"options\": [\"Froakie\", \"Chespin\", \"Fennekin\", \"Frogadier\"], \"answer\": \"Froakie\" }",
        "{ \"question\": \"Which Pokémon evolves into Chesnaught?\", \"options\": [\"Quilladin\", \"Chespin\", \"Braixen\", \"Frogadier\"], \"answer\": \"Quilladin\" }",
        "{ \"question\": \"Which Pokémon evolves into Delphox?\", \"options\": [\"Braixen\", \"Fennekin\", \"Chesnaught\", \"Frogadier\"], \"answer\": \"Braixen\" }",
        "{ \"question\": \"Which Pokémon evolves into Greninja?\", \"options\": [\"Frogadier\", \"Froakie\", \"Quilladin\", \"Bunnelby\"], \"answer\": \"Frogadier\" }",
        "{ \"question\": \"Which Kalos Pokémon is known as the Seed Pokémon?\", \"options\": [\"Chespin\", \"Froakie\", \"Fennekin\", \"Bunnelby\"], \"answer\": \"Chespin\" }",
        "{ \"question\": \"What type is Talonflame?\", \"options\": [\"Fire/Flying\", \"Fire\", \"Flying\", \"Fire/Steel\"], \"answer\": \"Fire/Flying\" }",
        "{ \"question\": \"Which Pokémon evolves from Fletchinder?\", \"options\": [\"Talonflame\", \"Fletchling\", \"Fletchinder\", \"Noivern\"], \"answer\": \"Talonflame\" }",
        "{ \"question\": \"Which Kalos Legendary Pokémon is known as the Aura Pokémon?\", \"options\": [\"Xerneas\", \"Yveltal\", \"Zygarde\", \"Diancie\"], \"answer\": \"Xerneas\" }",
        "{ \"question\": \"Which Kalos Legendary Pokémon represents destruction?\", \"options\": [\"Yveltal\", \"Xerneas\", \"Zygarde\", \"Volcanion\"], \"answer\": \"Yveltal\" }",
        "{ \"question\": \"Which Kalos Legendary Pokémon represents order and balance?\", \"options\": [\"Zygarde\", \"Xerneas\", \"Yveltal\", \"Diancie\"], \"answer\": \"Zygarde\" }",
        "{ \"question\": \"Which Pokémon evolves from Amaura?\", \"options\": [\"Aurorus\", \"Tyrunt\", \"Tyrantrum\", \"Amaura\"], \"answer\": \"Aurorus\" }",
        "{ \"question\": \"Which Pokémon evolves from Tyrunt?\", \"options\": [\"Tyrantrum\", \"Aurorus\", \"Tyrunt\", \"Tyranitar\"], \"answer\": \"Tyrantrum\" }",
        "{ \"question\": \"What type is Greninja?\", \"options\": [\"Water/Dark\", \"Water\", \"Dark\", \"Water/Ice\"], \"answer\": \"Water/Dark\" }",
        "{ \"question\": \"Which Pokémon is known as the Fox Pokémon in Kalos?\", \"options\": [\"Fennekin\", \"Braixen\", \"Delphox\", \"Ninetales\"], \"answer\": \"Fennekin\" }",
        "{ \"question\": \"Which Pokémon evolves from Braixen?\", \"options\": [\"Delphox\", \"Fennekin\", \"Chesnaught\", \"Greninja\"], \"answer\": \"Delphox\" }",
        "{ \"question\": \"What type is Sylveon?\", \"options\": [\"Fairy\", \"Normal\", \"Psychic\", \"Fairy/Psychic\"], \"answer\": \"Fairy\" }",
        "{ \"question\": \"Which Pokémon evolves into Sylveon?\", \"options\": [\"Eevee\", \"Vaporeon\", \"Jolteon\", \"Flareon\"], \"answer\": \"Eevee\" }",
        "{ \"question\": \"Which Pokémon is known as the Eevee Evolution with ribbons?\", \"options\": [\"Sylveon\", \"Espeon\", \"Leafeon\", \"Glaceon\"], \"answer\": \"Sylveon\" }",
        "{ \"question\": \"Which Pokémon is known as the Magnetic Pokémon in Kalos?\", \"options\": [\"Magnezone\", \"Magneton\", \"Magnezone\", \"Rotom\"], \"answer\": \"Magnezone\" }",
        "{ \"question\": \"Which Pokémon evolves from Magnemite in Kalos?\", \"options\": [\"Magneton\", \"Magnezone\", \"Rotom\", \"Magmar\"], \"answer\": \"Magneton\" }",
        "{ \"question\": \"Which Pokémon is the Legendary Pokémon of Kalos that can Mega Evolve?\", \"options\": [\"Xerneas\", \"Yveltal\", \"Zygarde\", \"Diancie\"], \"answer\": \"Diancie\" }",
        "{ \"question\": \"Which Kalos Pokémon is known as the Armored Pokémon?\", \"options\": [\"Aegislash\", \"Doublade\", \"Honedge\", \"Bisharp\"], \"answer\": \"Aegislash\" }",
        "{ \"question\": \"Which Pokémon evolves from Honedge?\", \"options\": [\"Doublade\", \"Aegislash\", \"Bisharp\", \"Klefki\"], \"answer\": \"Doublade\" }",
        "{ \"question\": \"Which Pokémon is the first in the Alola Pokédex?\", \"options\": [\"Rowlet\", \"Litten\", \"Popplio\", \"Pikipek\"], \"answer\": \"Rowlet\" }",
        "{ \"question\": \"What type is Rowlet?\", \"options\": [\"Grass/Flying\", \"Grass\", \"Flying\", \"Grass/Dark\"], \"answer\": \"Grass/Flying\" }",
        "{ \"question\": \"Which Alola starter is a Fire type?\", \"options\": [\"Litten\", \"Rowlet\", \"Popplio\", \"Incineroar\"], \"answer\": \"Litten\" }",
        "{ \"question\": \"Which Alola starter is a Water type?\", \"options\": [\"Popplio\", \"Rowlet\", \"Litten\", \"Primarina\"], \"answer\": \"Popplio\" }",
        "{ \"question\": \"Which Pokémon evolves into Decidueye?\", \"options\": [\"Dartrix\", \"Rowlet\", \"Litten\", \"Popplio\"], \"answer\": \"Dartrix\" }",
        "{ \"question\": \"Which Pokémon evolves into Incineroar?\", \"options\": [\"Torracat\", \"Litten\", \"Popplio\", \"Primarina\"], \"answer\": \"Torracat\" }",
        "{ \"question\": \"Which Pokémon evolves into Primarina?\", \"options\": [\"Brionne\", \"Popplio\", \"Rowlet\", \"Litten\"], \"answer\": \"Brionne\" }",
        "{ \"question\": \"Which Alola Pokémon is known as the Seed Pokémon?\", \"options\": [\"Rowlet\", \"Bounsweet\", \"Pikipek\", \"Litten\"], \"answer\": \"Rowlet\" }",
        "{ \"question\": \"What type is Lycanroc Midday Form?\", \"options\": [\"Rock\", \"Rock/Fighting\", \"Fighting\", \"Ground\"], \"answer\": \"Rock\" }",
        "{ \"question\": \"Which Pokémon evolves into Lycanroc Midday Form?\", \"options\": [\"Rockruff\", \"Lycanroc\", \"Midday Form\", \"Dusk Form\"], \"answer\": \"Rockruff\" }",
        "{ \"question\": \"Which Alola Legendary Pokémon is the guardian of Melemele Island?\", \"options\": [\"Tapu Koko\", \"Tapu Lele\", \"Tapu Bulu\", \"Tapu Fini\"], \"answer\": \"Tapu Koko\" }",
        "{ \"question\": \"Which Legendary Pokémon is the guardian of Akala Island?\", \"options\": [\"Tapu Lele\", \"Tapu Koko\", \"Tapu Bulu\", \"Tapu Fini\"], \"answer\": \"Tapu Lele\" }",
        "{ \"question\": \"Which Legendary Pokémon is the guardian of Ula'ula Island?\", \"options\": [\"Tapu Bulu\", \"Tapu Koko\", \"Tapu Lele\", \"Tapu Fini\"], \"answer\": \"Tapu Bulu\" }",
        "{ \"question\": \"Which Legendary Pokémon is the guardian of Poni Island?\", \"options\": [\"Tapu Fini\", \"Tapu Koko\", \"Tapu Lele\", \"Tapu Bulu\"], \"answer\": \"Tapu Fini\" }",
        "{ \"question\": \"What type is Solgaleo?\", \"options\": [\"Psychic/Steel\", \"Steel/Psychic\", \"Psychic\", \"Steel\"], \"answer\": \"Psychic/Steel\" }",
        "{ \"question\": \"What type is Lunala?\", \"options\": [\"Psychic/Ghost\", \"Psychic/Dark\", \"Ghost\", \"Psychic\"], \"answer\": \"Psychic/Ghost\" }",
        "{ \"question\": \"Which Pokémon evolves from Rockruff in Dusk Form?\", \"options\": [\"Lycanroc Dusk Form\", \"Lycanroc Midday Form\", \"Lycanroc Midnight Form\", \"Lycanroc\"], \"answer\": \"Lycanroc Dusk Form\" }",
        "{ \"question\": \"Which Pokémon is known as the Sunne Pokémon in Alola?\", \"options\": [\"Solgaleo\", \"Lunala\", \"Tapu Koko\", \"Necrozma\"], \"answer\": \"Solgaleo\" }",
        "{ \"question\": \"Which Pokémon is known as the Moone Pokémon in Alola?\", \"options\": [\"Lunala\", \"Solgaleo\", \"Tapu Lele\", \"Necrozma\"], \"answer\": \"Lunala\" }",
        "{ \"question\": \"Which Pokémon is known as the Prism Pokémon?\", \"options\": [\"Necrozma\", \"Solgaleo\", \"Lunala\", \"Cosmoem\"], \"answer\": \"Necrozma\" }",
        "{ \"question\": \"Which Pokémon evolves from Cosmoem into Dusk Mane Necrozma?\", \"options\": [\"Solgaleo\", \"Lunala\", \"Necrozma\", \"Cosmog\"], \"answer\": \"Necrozma\" }",
        "{ \"question\": \"Which Pokémon evolves from Cosmoem into Dawn Wings Necrozma?\", \"options\": [\"Lunala\", \"Solgaleo\", \"Necrozma\", \"Cosmog\"], \"answer\": \"Lunala\" }",
        "{ \"question\": \"Which Pokémon is known as the Bean Pokémon in Alola?\", \"options\": [\"Bounsweet\", \"Steenee\", \"Tsareena\", \"Comfey\"], \"answer\": \"Bounsweet\" }",
        "{ \"question\": \"Which Pokémon evolves into Tsareena?\", \"options\": [\"Steenee\", \"Bounsweet\", \"Comfey\", \"Oricorio\"], \"answer\": \"Steenee\" }",
        "{ \"question\": \"Which Pokémon is known as the Hula Pokémon?\", \"options\": [\"Oricorio\", \"Litten\", \"Rowlet\", \"Torracat\"], \"answer\": \"Oricorio\" }",
        "{ \"question\": \"Which Pokémon has four different dance forms in Alola?\", \"options\": [\"Oricorio\", \"Lycanroc\", \"Minior\", \"Alolan Raichu\"], \"answer\": \"Oricorio\" }",
        "{ \"question\": \"Which Pokémon is the first in the Galar Pokédex?\", \"options\": [\"Grookey\", \"Scorbunny\", \"Sobble\", \"Rookidee\"], \"answer\": \"Grookey\" }",
        "{ \"question\": \"What type is Grookey?\", \"options\": [\"Grass\", \"Grass/Fighting\", \"Grass/Normal\", \"Grass/Poison\"], \"answer\": \"Grass\" }",
        "{ \"question\": \"Which Galar starter is a Fire type?\", \"options\": [\"Scorbunny\", \"Grookey\", \"Sobble\", \"Raboot\"], \"answer\": \"Scorbunny\" }",
        "{ \"question\": \"Which Galar starter is a Water type?\", \"options\": [\"Sobble\", \"Grookey\", \"Scorbunny\", \"Drizzile\"], \"answer\": \"Sobble\" }",
        "{ \"question\": \"Which Pokémon evolves into Rillaboom?\", \"options\": [\"Thwackey\", \"Grookey\", \"Scorbunny\", \"Raboot\"], \"answer\": \"Thwackey\" }",
        "{ \"question\": \"Which Pokémon evolves into Cinderace?\", \"options\": [\"Raboot\", \"Scorbunny\", \"Grookey\", \"Drizzile\"], \"answer\": \"Raboot\" }",
        "{ \"question\": \"Which Pokémon evolves into Inteleon?\", \"options\": [\"Drizzile\", \"Sobble\", \"Grookey\", \"Scorbunny\"], \"answer\": \"Drizzile\" }",
        "{ \"question\": \"Which Galar Pokémon is known as the Monkey Pokémon?\", \"options\": [\"Grookey\", \"Raboot\", \"Thwackey\", \"Inteleon\"], \"answer\": \"Grookey\" }",
        "{ \"question\": \"Which Galar Pokémon is known as the Rabbit Pokémon?\", \"options\": [\"Scorbunny\", \"Raboot\", \"Cinderace\", \"Grookey\"], \"answer\": \"Scorbunny\" }",
        "{ \"question\": \"Which Galar Pokémon is known as the Secret Agent Pokémon?\", \"options\": [\"Inteleon\", \"Sobble\", \"Drizzile\", \"Galarian Slowpoke\"], \"answer\": \"Inteleon\" }",
        "{ \"question\": \"What type is Dragapult?\", \"options\": [\"Dragon/Ghost\", \"Dragon\", \"Ghost\", \"Dragon/Dark\"], \"answer\": \"Dragon/Ghost\" }",
        "{ \"question\": \"Which Pokémon evolves from Drakloak?\", \"options\": [\"Dragapult\", \"Dreepy\", \"Drakloak\", \"Dragalge\"], \"answer\": \"Dragapult\" }",
        "{ \"question\": \"Which Galar Legendary is known as the Hero of Many Battles?\", \"options\": [\"Zacian\", \"Zamazenta\", \"Eternatus\", \"Calyrex\"], \"answer\": \"Zacian\" }",
        "{ \"question\": \"Which Galar Legendary is known as the Hero of Many Battles' Shield?\", \"options\": [\"Zamazenta\", \"Zacian\", \"Eternatus\", \"Calyrex\"], \"answer\": \"Zamazenta\" }",
        "{ \"question\": \"Which Galar Legendary represents Dynamax energy?\", \"options\": [\"Eternatus\", \"Zacian\", \"Zamazenta\", \"Calyrex\"], \"answer\": \"Eternatus\" }",
        "{ \"question\": \"Which Pokémon is the Ice Rider of Galar?\", \"options\": [\"Calyrex\", \"Glastrier\", \"Spectrier\", \"Zamazenta\"], \"answer\": \"Glastrier\" }",
        "{ \"question\": \"Which Pokémon is the Shadow Rider of Galar?\", \"options\": [\"Spectrier\", \"Glastrier\", \"Calyrex\", \"Zacian\"], \"answer\": \"Spectrier\" }",
        "{ \"question\": \"What type is Coalossal?\", \"options\": [\"Rock/Fire\", \"Rock\", \"Fire\", \"Fire/Steel\"], \"answer\": \"Rock/Fire\" }",
        "{ \"question\": \"Which Pokémon evolves from Carkol?\", \"options\": [\"Coalossal\", \"Rolycoly\", \"Sizzlipede\", \"Centiskorch\"], \"answer\": \"Coalossal\" }",
        "{ \"question\": \"Which Galar Pokémon is known as the Fox Pokémon?\", \"options\": [\"Fennekin\", \"Galarian Zigzagoon\", \"Nickit\", \"Zorua\"], \"answer\": \"Nickit\" }",
        "{ \"question\": \"Which Pokémon evolves from Nickit?\", \"options\": [\"Thievul\", \"Zorua\", \"Nickit\", \"Zoroark\"], \"answer\": \"Thievul\" }",
        "{ \"question\": \"Which Galar Pokémon is known as the Wolf Pokémon?\", \"options\": [\"Boltund\", \"Zacian\", \"Zamazenta\", \"Lycanroc\"], \"answer\": \"Boltund\" }",
        "{ \"question\": \"Which Pokémon evolves from Yamper?\", \"options\": [\"Boltund\", \"Yamper\", \"Rookidee\", \"Corviknight\"], \"answer\": \"Boltund\" }",
        "{ \"question\": \"Which Galar Pokémon is known as the Raven Pokémon?\", \"options\": [\"Corviknight\", \"Rookidee\", \"Corvisquire\", \"Honchkrow\"], \"answer\": \"Corviknight\" }",
        "{ \"question\": \"Which Pokémon evolves from Rookidee?\", \"options\": [\"Corvisquire\", \"Corviknight\", \"Rookidee\", \"Honchkrow\"], \"answer\": \"Corvisquire\" }",
        "{ \"question\": \"Which Galar Pokémon is known as the Centipede Pokémon?\", \"options\": [\"Sizzlipede\", \"Centiskorch\", \"Rolycoly\", \"Carkol\"], \"answer\": \"Sizzlipede\" }",
        "{ \"question\": \"Which Pokémon evolves from Sizzlipede?\", \"options\": [\"Centiskorch\", \"Carkol\", \"Coalossal\", \"Rolycoly\"], \"answer\": \"Centiskorch\" }"
    )

}